#
# Makefile for ICT CAS loongson3a board.
#

#obj-y	+= setup.o prom.o reset.o irq.o pci.o bonito-irq.o mipsdha.o dbg_io.o mem.o 
obj-y	+= irq.o reset.o dbg_io.o

obj-$(CONFIG_SMP)	+= smp.o

obj-$(CONFIG_NUMA)	+= numa.o
#EXTRA_AFLAGS := $(CFLAGS)
